"""Add eye_pattern columns to user

Revision ID: d085ba610dae
Revises: 
Create Date: 2024-12-31 14:13:24.972594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd085ba610dae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_pattern_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('eye_pattern_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('eye_pattern_3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('eye_pattern_4', sa.String(), nullable=True))
        batch_op.drop_column('eye_patterns')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_patterns', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('eye_pattern_4')
        batch_op.drop_column('eye_pattern_3')
        batch_op.drop_column('eye_pattern_2')
        batch_op.drop_column('eye_pattern_1')

    # ### end Alembic commands ###
